INSERT INTO EXT_FILE_PARAMS
(COD_XF_SYSTEM,FILE_TYPE,NAM_XF_SYSTEM,NAM_FILE_TYPE,NAM_UPLOAD_TMPL,FLG_OUTPUT_REQD,NAM_OUTPUT_TMPL,FLG_AUTH_REQD,FLG_ALLOW_REVERSAL,FLG_REPORT_GEN,FLG_FILE_TRANSACTIONAL,CTR_COMMIT_SIZE,CTR_PARALLEL_STREAMS,COD_BRIDGE_INTXF_DR,COD_BRIDGE_INTXF_CR,COD_BRIDGE_CASH_DR,COD_BRIDGE_CASH_CR,COD_SUSPENSE_GL_DR,COD_SUSPENSE_GL_CR,FLG_GENERATE_BRIDGE_GL,FLG_GENERATE_IB_GL,COD_DESG_BRN,FLG_BALANCE_BRIDGE,DAT_LAST_MNT,FLG_MNT_STATUS,COD_LAST_MNT_MAKERID,COD_LAST_MNT_CHKRID,COD_MNT_ACTION,CTR_UPDAT_SRLNO,XF_FILE_NAME,PROCESSOR_TYPE,FLG_FORMAT,FLG_DIRECTION,PROCESS_SP_NAME,OUTPUT_FLD_HLP_CLASS,OUTPUT_FILE_HLP_CLASS,DAT_LAST_EXTRACT,FLG_ENCRYP_REQ,ALGORITHM_NAME,RELATIVE_PATH,COD_ENCR_KEY)
VALUES
('GEFU','GEFUGEFU','GEFU','GEFUGEFU','OdbulkupldFileDefn.xml','N',NULL,'N','N','Y','N',3,3,100077000,100099000,100077000,100099000,100099000,100077000,'Y','Y',1,'N','3-JAN-2006','A','SYSTELLER','SYSSUPER',NULL,1,NULL,'U','X','O',NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL)
/
i have changed this 
